altered styling of project page and removed search filters
open-austin/website-v2-vercel pull request #24
Opened 2022-11-24 03:53 UTC by attali-david

#15

2022-11-25 19:55 UTC, lianilychee commented
We can merge once the H2 fix requests get resolved. The other two are minor comments.

2022-11-26 01:13 UTC, lianilychee requested changes

2022-11-26 23:25 UTC, attali-david commented on components/completedProjectList.tsx
> +      <Text>Completed Work</Text>
Yes! I held off on styling until I could get confirmation the layout was what you envisioned. I'll fix the styling now.

2022-11-26 23:26 UTC, attali-david commented on components/completedProjectList.tsx
> +        Here are a few of our complete work. For all of our projects visit our
This was an oversight on my part. I think either works.

2022-11-27 00:36 UTC, merged

2022-11-27 21:36 UTC, newswim commented on components/completedProjectList.tsx
> +        <Link> Github</Link>.
I would tend to call it a "GitHub Repo", but "GitHub Page" might be a little more approachable (and more accurate than just saying, "Our GitHub".

2022-11-27 21:55 UTC, newswim commented
@attali-david since we're no longer using it, you can go ahead and remove `'chakra-react-select'` for the project dependencies.

2022-11-27 22:22 UTC, lianilychee commented on components/completedProjectList.tsx
> +        <Link> Github</Link>.
Thanks! Already merged this PR, but referenced you comment in a new issue