Refactored types
open-austin/website-v2-vercel pull request #3
Opened 2022-10-15 20:32 UTC by attali-david

2022-10-21 16:54 UTC, newswim requested changes

2022-10-21 16:54 UTC, newswim commented on types.ts
> +export type SearchBarProps = {
I think it's preferable to co-locate these with the components. They really shouldn't be used by any other functions, unless those functions also operate on the component.

2022-10-21 16:57 UTC, newswim commented on types.ts
> +export type SearchBarProps = {
Co-locating all of the types is a case of organizing things by what they "are" versus what they "do" (it's kind of a slippery distinction). In general, it's easier to understand the behavior of the system when the relevant parts are nearby. In this case, you're dealing with props in a component so it's really helpful to have the type definition within arm's reach.

Another example might be if there were other operations / helper functions that this specific component used. I've seen a pattern where people put those functions into a `helpers.ts` file, and then that file grows to be thousands of lines long, because someone sees that file are thinks "Oh, this is a helper, I put it in the helper file". Instead of thinking about how it's used, and thinking more in terms of the entities (nouns) and operations (verbs) of the system.

2022-10-21 17:00 UTC, newswim commented on types/Projects.ts
> -  title: string
I started this pattern because the "Projects" are a larger concept that isn't used by one specific component, but several in different ways. I know it's tricky to get code organized in a way that feels intuitive.. and at the end of the day, it's really all about taste. There's nothing wrong with the changes here, but I feel like they encourage a potentially bad pattern as projects grow in size.

2022-11-23 05:07 UTC, attali-david commented
Should we go ahead and close this branch @newswim ?

2023-01-24 05:08 UTC, closed without merging